# A basic apache server. To use either add or bind mount content under /var/www
FROM gocd/gocd-agent-ubuntu-14.04:v18.1.0

RUN sudo apt-get update -y
RUN sudo apt-get install nodejs -y
RUN sudo apt-get install npm -y